//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFS.Tools {
    
    public partial class script_runner {
        protected System.Web.UI.HtmlControls.HtmlForm Form1;
        protected System.Web.UI.WebControls.Label Label1;
        protected System.Web.UI.WebControls.Button btnExecuteDll;
        protected System.Web.UI.WebControls.Button btnExecuteReader;
        protected System.Web.UI.WebControls.Label Label3;
        protected System.Web.UI.WebControls.TextBox script;
        protected System.Web.UI.WebControls.Label Label2;
        protected System.Web.UI.WebControls.Button btnExecuteNonQuery;
        protected System.Web.UI.WebControls.TextBox results;
        protected System.Web.UI.WebControls.Button btnClear;
    }
}
