//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquiForce.LFSLive.WebUI.CWP.Jliner {
    
    public partial class jliner_bulk_date_update {
        protected System.Web.UI.WebControls.Wizard Wizard;
        protected System.Web.UI.WebControls.WizardStep Begin;
        protected System.Web.UI.WebControls.Label lblFieldToUpdate;
        protected System.Web.UI.WebControls.DropDownList ddlFieldToUpdate;
        protected System.Web.UI.WebControls.RequiredFieldValidator rfvFieldToUpdate;
        protected System.Web.UI.WebControls.Label lblDate;
        protected System.Web.UI.WebControls.TextBox tbxDate;
        protected System.Web.UI.WebControls.CompareValidator cvDate;
        protected System.Web.UI.WebControls.WizardStep Finish;
        protected System.Web.UI.WebControls.TextBox tbxSummary;
        protected System.Web.UI.WebControls.HiddenField hdfCurrentClient;
        protected System.Web.UI.WebControls.HiddenField hdfUpdate;
        protected System.Web.UI.WebControls.HiddenField hdfStep;
    }
}
