using System;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;

namespace LiquiForce.LFSLive.CWP.DatabaseGateway
{
	public class LFSRecordForNavigatorGateway
	{
		///////////////////////////////////////////////////////////////////////////
		/// PROPERTIES AND FIELDS
		///

		private string ConnectionString;






		///////////////////////////////////////////////////////////////////////////
		/// CONSTRUCTORS
		///

		//
		// Default
		//
		public LFSRecordForNavigatorGateway()
		{
			//--- Get the connection string
			AppSettingsReader appSettingReader = new AppSettingsReader();
			ConnectionString = appSettingReader.GetValue("ConnectionString", typeof(System.String)).ToString();
		}






		///////////////////////////////////////////////////////////////////////////
		/// METHODS
		///

		//
		// GetRecordsByCompanyIdRecordIdTargetPage()
		//
		// Returns target page's records that match an RecordID (where RecordID like recordId%) ordered by RecordID
		// 
		public TDSLFSRecordForNavigator GetRecordsByCompanyIdRecordIdTargetPage(int companyId, string recordId, string targetPage)
		{
			SqlConnection connection = new SqlConnection(ConnectionString);

			string commandText = "";
			switch(targetPage)
			{
				case "view_all.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected  FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.RecordID LIKE @recordId) AND (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_fulllength.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.RecordID LIKE @recordId) AND (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (LFS_MASTER_AREA.FullLengthLining = 1) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_pointliner.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.RecordID LIKE @recordId) AND (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND ( (LFS_MASTER_AREA.PointLining = 1) OR (LFS_MASTER_AREA.Grouting = 1) OR (LFS_MASTER_AREA.LateralLining = 1) OR (LFS_MASTER_AREA.JLiner = 1) OR (LFS_MASTER_AREA.RehabAssessment = 1) ) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_scopesheet.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.RecordID LIKE @recordId) AND (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (LFS_MASTER_AREA.PointLining = 1) AND (LFS_MASTER_AREA.IssueIdentified = 0) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_subcontractor.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.RecordID LIKE @recordId) AND (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (LFS_MASTER_AREA.SubcontractorLining = 1) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_jlinersheet.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.RecordID LIKE @recordId) AND (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (LFS_MASTER_AREA.JLiner = 1) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.RecordID DESC";
					break;
			}
			
			SqlCommand command = new SqlCommand(commandText, connection);
			command.Parameters.Add(new SqlParameter("@recordId", recordId + "%"));
			command.Parameters.Add(new SqlParameter("@companyId", companyId));

			SqlDataAdapter dataAdapter = new SqlDataAdapter(command);

			TDSLFSRecordForNavigator dataSet = new TDSLFSRecordForNavigator();
			dataAdapter.Fill(dataSet, "NAVIGATOR");
			
			return dataSet;
		}



		//
		// GetRecordsByCompanyIdClientTargetPage()
		//
		// Returns target page's records that match a Client name (where Name like %cleint%) ordered by client, recordId
		// 
		public TDSLFSRecordForNavigator GetRecordsByCompanyIdClientTargetPage(int companyId, string client, string targetPage)
		{
			//--- Prepare search condition
			string[] tokens = client.Split(new char[]{' ',',',';','.',':','-','_','\\','/'}, 50);
			string condition = null;
			for (int i=0; i<tokens.Length; i++)
			{
				if (i==0)
				{
					condition = "COMPANIES.NAME LIKE '%" + tokens[i].ToString() + "%' ";
				}
				else
				{
					condition += "AND COMPANIES.NAME LIKE '%" + tokens[i].ToString() + "%' ";
				}
			}

			//--- Execute query
			SqlConnection connection = new SqlConnection(ConnectionString);

			string commandText = "";
			switch(targetPage)
			{
				case "view_all.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (" + condition + ") AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY COMPANIES.NAME, LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_fulllength.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (" + condition + ") AND (LFS_MASTER_AREA.FullLengthLining = 1) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY COMPANIES.NAME, LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_pointliner.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (" + condition + ") AND ( (LFS_MASTER_AREA.PointLining = 1) OR (LFS_MASTER_AREA.Grouting = 1) OR (LFS_MASTER_AREA.LateralLining = 1) OR (LFS_MASTER_AREA.JLiner = 1) OR (LFS_MASTER_AREA.RehabAssessment = 1) ) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY COMPANIES.NAME, LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_scopesheet.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (" + condition + ") AND (LFS_MASTER_AREA.PointLining = 1) AND (LFS_MASTER_AREA.IssueIdentified = 0) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY COMPANIES.NAME, LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_subcontractor.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (" + condition + ") AND (LFS_MASTER_AREA.SubcontractorLining = 1) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY COMPANIES.NAME, LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_jlinersheet.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (" + condition + ") AND (LFS_MASTER_AREA.JLiner = 1) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY COMPANIES.NAME, LFS_MASTER_AREA.RecordID DESC";
					break;
			}
			
			SqlCommand command = new SqlCommand(commandText, connection);
			command.Parameters.Add(new SqlParameter("@companyId", companyId));

			SqlDataAdapter dataAdapter = new SqlDataAdapter(command);

			TDSLFSRecordForNavigator dataSet = new TDSLFSRecordForNavigator();
			dataAdapter.Fill(dataSet, "NAVIGATOR");
			
			return dataSet;
		}



		//
		// GetRecordsByCompanyIdUsmhTargetPage()
		//
		// Returns target page's records that match an usmh (where usmh like usmh%) ordered by usmh
		// 
		public TDSLFSRecordForNavigator GetRecordsByCompanyIdUsmhTargetPage(int companyId, string usmh, string targetPage)
		{
			SqlConnection connection = new SqlConnection(ConnectionString);

			string commandText = "";
			switch(targetPage)
			{
				case "view_all.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (LFS_MASTER_AREA.USMH LIKE @usmh) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_fulllength.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (LFS_MASTER_AREA.USMH LIKE @usmh) AND (LFS_MASTER_AREA.FullLengthLining = 1) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_pointliner.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (LFS_MASTER_AREA.USMH LIKE @usmh) AND ( (LFS_MASTER_AREA.PointLining = 1) OR (LFS_MASTER_AREA.Grouting = 1) OR (LFS_MASTER_AREA.LateralLining = 1) OR (LFS_MASTER_AREA.JLiner = 1) OR (LFS_MASTER_AREA.RehabAssessment = 1) ) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_scopesheet.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (LFS_MASTER_AREA.USMH LIKE @usmh) AND (LFS_MASTER_AREA.PointLining = 1) AND (LFS_MASTER_AREA.IssueIdentified = 0) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_subcontractor.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (LFS_MASTER_AREA.USMH LIKE @usmh) AND (LFS_MASTER_AREA.SubcontractorLining = 1) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_jlinersheet.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (LFS_MASTER_AREA.USMH LIKE @usmh) AND (LFS_MASTER_AREA.JLiner = 1) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.RecordID DESC";
					break;
			}

			SqlCommand command = new SqlCommand(commandText, connection);
			command.Parameters.Add(new SqlParameter("@companyId", companyId));
			command.Parameters.Add(new SqlParameter("@usmh", usmh + "%"));
			
			SqlDataAdapter dataAdapter = new SqlDataAdapter(command);

			TDSLFSRecordForNavigator dataSet = new TDSLFSRecordForNavigator();
			dataAdapter.Fill(dataSet, "NAVIGATOR");
			
			return dataSet;
		}



		//
		// GetRecordsByCompanyIdDsmhTargetPage()
		//
		// Returns target page's records that match a dsmh (where dsmh like dsmh%) ordered by dsmh
		// 
		public TDSLFSRecordForNavigator GetRecordsByCompanyIdDsmhTargetPage(int companyId, string dsmh, string targetPage)
		{
			SqlConnection connection = new SqlConnection(ConnectionString);

			string commandText = "";
			switch(targetPage)
			{
				case "view_all.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (LFS_MASTER_AREA.DSMH LIKE @dsmh) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_fulllength.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (LFS_MASTER_AREA.DSMH LIKE @dsmh) AND (LFS_MASTER_AREA.FullLengthLining = 1) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_pointliner.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (LFS_MASTER_AREA.DSMH LIKE @dsmh) AND ( (LFS_MASTER_AREA.PointLining = 1) OR (LFS_MASTER_AREA.Grouting = 1) OR (LFS_MASTER_AREA.LateralLining = 1) OR (LFS_MASTER_AREA.JLiner = 1) OR (LFS_MASTER_AREA.RehabAssessment = 1) ) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_scopesheet.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (LFS_MASTER_AREA.DSMH LIKE @dsmh) AND (LFS_MASTER_AREA.PointLining = 1) AND (LFS_MASTER_AREA.IssueIdentified = 0) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_subcontractor.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (LFS_MASTER_AREA.DSMH LIKE @dsmh) AND (LFS_MASTER_AREA.SubcontractorLining = 1) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_jlinersheet.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (LFS_MASTER_AREA.DSMH LIKE @dsmh) AND (LFS_MASTER_AREA.JLiner = 1) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.RecordID DESC";
					break;
			}

			SqlCommand command = new SqlCommand(commandText, connection);
			command.Parameters.Add(new SqlParameter("@companyId", companyId));
			command.Parameters.Add(new SqlParameter("@dsmh", dsmh + "%"));
			
			SqlDataAdapter dataAdapter = new SqlDataAdapter(command);

			TDSLFSRecordForNavigator dataSet = new TDSLFSRecordForNavigator();
			dataAdapter.Fill(dataSet, "NAVIGATOR");
			
			return dataSet;
		}



		//
		// GetRecordsByCompanyIdP1DateTargetPage()
		//
		// Returns target page's records that match a p1 date (where p1 date = p1Date) ordered by recordId
		// 
		public TDSLFSRecordForNavigator GetRecordsByCompanyIdP1DateTargetPage(int companyId, DateTime p1Date, string targetPage)
		{
			SqlConnection connection = new SqlConnection(ConnectionString);

			string commandText = "";
			switch(targetPage)
			{
				case "view_all.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (LFS_MASTER_AREA.P1Date = @p1Date) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_fulllength.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (LFS_MASTER_AREA.P1Date = @p1Date) AND (LFS_MASTER_AREA.FullLengthLining = 1) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_pointliner.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (LFS_MASTER_AREA.P1Date = @p1Date) AND ( (LFS_MASTER_AREA.PointLining = 1) OR (LFS_MASTER_AREA.Grouting = 1) OR (LFS_MASTER_AREA.LateralLining = 1) OR (LFS_MASTER_AREA.JLiner = 1) OR (LFS_MASTER_AREA.RehabAssessment = 1) ) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_scopesheet.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (LFS_MASTER_AREA.P1Date = @p1Date) AND (LFS_MASTER_AREA.PointLining = 1) AND (LFS_MASTER_AREA.IssueIdentified = 0) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_subcontractor.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (LFS_MASTER_AREA.P1Date = @p1Date) AND (LFS_MASTER_AREA.SubcontractorLining = 1) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_jlinersheet.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (LFS_MASTER_AREA.P1Date = @p1Date) AND (LFS_MASTER_AREA.JLiner = 1) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.RecordID DESC";
					break;
			}

			SqlCommand command = new SqlCommand(commandText, connection);
			command.Parameters.Add(new SqlParameter("@companyId", companyId));
			command.Parameters.Add(new SqlParameter("@p1Date", p1Date));
			
			SqlDataAdapter dataAdapter = new SqlDataAdapter(command);

			TDSLFSRecordForNavigator dataSet = new TDSLFSRecordForNavigator();
			dataAdapter.Fill(dataSet, "NAVIGATOR");
			
			return dataSet;
		}



		//
		// GetRecordsByCompanyIdM1DateTargetPage()
		//
		// Returns target page's records that match a m1 date (where m1 date = m1Date) ordered by recordId
		// 
		public TDSLFSRecordForNavigator GetRecordsByCompanyIdM1DateTargetPage(int companyId, DateTime m1Date, string targetPage)
		{
			SqlConnection connection = new SqlConnection(ConnectionString);

			string commandText = "";
			switch(targetPage)
			{
				case "view_all.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (LFS_MASTER_AREA.M1Date = @m1Date) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_fulllength.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (LFS_MASTER_AREA.M1Date = @m1Date) AND (LFS_MASTER_AREA.FullLengthLining = 1) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_pointliner.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (LFS_MASTER_AREA.M1Date = @m1Date) AND ( (LFS_MASTER_AREA.PointLining = 1) OR (LFS_MASTER_AREA.Grouting = 1) OR (LFS_MASTER_AREA.LateralLining = 1) OR (LFS_MASTER_AREA.JLiner = 1) OR (LFS_MASTER_AREA.RehabAssessment = 1) ) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_scopesheet.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (LFS_MASTER_AREA.M1Date = @m1Date) AND (LFS_MASTER_AREA.PointLining = 1) AND (LFS_MASTER_AREA.IssueIdentified = 0) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_subcontractor.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (LFS_MASTER_AREA.M1Date = @m1Date) AND (LFS_MASTER_AREA.SubcontractorLining = 1) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_jlinersheet.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (LFS_MASTER_AREA.M1Date = @m1Date) AND (LFS_MASTER_AREA.JLiner = 1) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.RecordID DESC";
					break;
			}

			SqlCommand command = new SqlCommand(commandText, connection);
			command.Parameters.Add(new SqlParameter("@companyId", companyId));
			command.Parameters.Add(new SqlParameter("@m1Date", m1Date));
			
			SqlDataAdapter dataAdapter = new SqlDataAdapter(command);

			TDSLFSRecordForNavigator dataSet = new TDSLFSRecordForNavigator();
			dataAdapter.Fill(dataSet, "NAVIGATOR");
			
			return dataSet;
		}



		//
		// GetRecordsByCompanyIdM2DateTargetPage()
		//
		// Returns target page's records that match a m2 date (where m2 date = m2Date) ordered by recordId
		// 
		public TDSLFSRecordForNavigator GetRecordsByCompanyIdM2DateTargetPage(int companyId, DateTime m2Date, string targetPage)
		{
			SqlConnection connection = new SqlConnection(ConnectionString);

			string commandText = "";
			switch(targetPage)
			{
				case "view_all.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (LFS_MASTER_AREA.M2Date = @m2Date) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_fulllength.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (LFS_MASTER_AREA.M2Date = @m2Date) AND (LFS_MASTER_AREA.FullLengthLining = 1) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_pointliner.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (LFS_MASTER_AREA.M2Date = @m2Date) AND ( (LFS_MASTER_AREA.PointLining = 1) OR (LFS_MASTER_AREA.Grouting = 1) OR (LFS_MASTER_AREA.LateralLining = 1) OR (LFS_MASTER_AREA.JLiner = 1) OR (LFS_MASTER_AREA.RehabAssessment = 1) ) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_scopesheet.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (LFS_MASTER_AREA.M2Date = @m2Date) AND (LFS_MASTER_AREA.PointLining = 1) AND (LFS_MASTER_AREA.IssueIdentified = 0) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_subcontractor.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (LFS_MASTER_AREA.M2Date = @m2Date) AND (LFS_MASTER_AREA.SubcontractorLining = 1) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_jlinersheet.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (LFS_MASTER_AREA.M2Date = @m2Date) AND (LFS_MASTER_AREA.JLiner = 1) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.RecordID DESC";
					break;
			}

			SqlCommand command = new SqlCommand(commandText, connection);
			command.Parameters.Add(new SqlParameter("@companyId", companyId));
			command.Parameters.Add(new SqlParameter("@m2Date", m2Date));
			
			SqlDataAdapter dataAdapter = new SqlDataAdapter(command);

			TDSLFSRecordForNavigator dataSet = new TDSLFSRecordForNavigator();
			dataAdapter.Fill(dataSet, "NAVIGATOR");
			
			return dataSet;
		}



		//
		// GetRecordsByCompanyIdInstallDateTargetPage()
		//
		// Returns target page's records that match a proposed lining date (where proposed lining date = proposedLiningDate) ordered by recordId
		// 
		public TDSLFSRecordForNavigator GetRecordsByCompanyIdInstallDateTargetPage(int companyId, DateTime installDate, string targetPage)
		{
			SqlConnection connection = new SqlConnection(ConnectionString);

			string commandText = "";
			switch(targetPage)
			{
				case "view_all.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (LFS_MASTER_AREA.InstallDate = @installDate) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_fulllength.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (LFS_MASTER_AREA.InstallDate = @installDate) AND (LFS_MASTER_AREA.FullLengthLining = 1) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_pointliner.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (LFS_MASTER_AREA.InstallDate = @installDate) AND ( (LFS_MASTER_AREA.PointLining = 1) OR (LFS_MASTER_AREA.Grouting = 1) OR (LFS_MASTER_AREA.LateralLining = 1) OR (LFS_MASTER_AREA.JLiner = 1) OR (LFS_MASTER_AREA.RehabAssessment = 1) ) OAND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) RDER BY LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_scopesheet.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (LFS_MASTER_AREA.InstallDate = @installDate) AND (LFS_MASTER_AREA.PointLining = 1) AND (LFS_MASTER_AREA.IssueIdentified = 0) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_subcontractor.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (LFS_MASTER_AREA.InstallDate = @installDate) AND (LFS_MASTER_AREA.SubcontractorLining = 1) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_jlinersheet.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (LFS_MASTER_AREA.InstallDate = @installDate) AND (LFS_MASTER_AREA.JLiner = 1) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.RecordID DESC";
					break;
			}

			SqlCommand command = new SqlCommand(commandText, connection);
			command.Parameters.Add(new SqlParameter("@companyId", companyId));
			command.Parameters.Add(new SqlParameter("@installDate", installDate));
						
			SqlDataAdapter dataAdapter = new SqlDataAdapter(command);

			TDSLFSRecordForNavigator dataSet = new TDSLFSRecordForNavigator();
			dataAdapter.Fill(dataSet, "NAVIGATOR");
			
			return dataSet;
		}



		//
		// GetRecordsByCompanyIdStreetTargetPage()
		//
		// Returns target page's records that match a street (where street like street%) ordered by street
		// 
		public TDSLFSRecordForNavigator GetRecordsByCompanyIdStreetTargetPage(int companyId, string street, string targetPage)
		{
			//--- Prepare search condition
			string[] tokens = street.Split(new char[]{' ',',',';','.',':','-','_','\\','/'}, 50);
			string condition = null;
			for (int i=0; i<tokens.Length; i++)
			{
				if (i==0)
				{
					condition = "LFS_MASTER_AREA.Street LIKE '%" + tokens[i].ToString() + "%' ";
				}
				else
				{
					condition += "AND LFS_MASTER_AREA.Street LIKE '%" + tokens[i].ToString() + "%' ";
				}
			}

			//--- Execute query
			SqlConnection connection = new SqlConnection(ConnectionString);

			string commandText = "";
			switch(targetPage)
			{
				case "view_all.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (" + condition + ") AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.Street, LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_fulllength.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (" + condition + ") AND (LFS_MASTER_AREA.FullLengthLining = 1) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.Street, LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_pointliner.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (" + condition + ") AND ( (LFS_MASTER_AREA.PointLining = 1) OR (LFS_MASTER_AREA.Grouting = 1) OR (LFS_MASTER_AREA.LateralLining = 1) OR (LFS_MASTER_AREA.JLiner = 1) OR (LFS_MASTER_AREA.RehabAssessment = 1) ) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.Street, LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_scopesheet.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (" + condition + ") AND (LFS_MASTER_AREA.PointLining = 1) AND (LFS_MASTER_AREA.IssueIdentified = 0) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.Street, LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_subcontractor.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (" + condition + ") AND (LFS_MASTER_AREA.SubcontractorLining = 1) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.Street, LFS_MASTER_AREA.RecordID DESC";
					break;

				case "view_jlinersheet.aspx":
                    commandText = "SELECT LFS_MASTER_AREA.ID, LFS_MASTER_AREA.COMPANY_ID, LFS_MASTER_AREA.RecordID, LFS_MASTER_AREA.COMPANIES_ID, COMPANIES.NAME, LFS_MASTER_AREA.Street, LFS_MASTER_AREA.USMH, LFS_MASTER_AREA.DSMH, LFS_MASTER_AREA.P1Date, LFS_MASTER_AREA.M1Date, LFS_MASTER_AREA.M2Date, LFS_MASTER_AREA.InstallDate, LFS_MASTER_AREA.Deleted, LFS_MASTER_AREA.Archived, CAST (0 AS BIT) AS Selected FROM LFS_MASTER_AREA INNER JOIN LFS_RESOURCES_COMPANIES AS COMPANIES ON LFS_MASTER_AREA.COMPANIES_ID = COMPANIES.COMPANIES_ID WHERE (LFS_MASTER_AREA.COMPANY_ID = @companyId) AND (" + condition + ") AND (LFS_MASTER_AREA.JLiner = 1) AND (LFS_MASTER_AREA.Deleted = 0) AND (LFS_MASTER_AREA.Archived = 0) ORDER BY LFS_MASTER_AREA.Street, LFS_MASTER_AREA.RecordID DESC";
					break;
			}
			
			SqlCommand command = new SqlCommand(commandText, connection);
			command.Parameters.Add(new SqlParameter("@companyId", companyId));

			SqlDataAdapter dataAdapter = new SqlDataAdapter(command);

			TDSLFSRecordForNavigator dataSet = new TDSLFSRecordForNavigator();
			dataAdapter.Fill(dataSet, "NAVIGATOR");
			
			return dataSet;
		}


	}
}
